/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "name": "John Doe",
         *       "phoneNumber": "+1234567890",
         *       "shopName": "My Shop",
         *       "address": "123 Main St, City, State",
         *       "numberOfCashiers": 2
         *     }
         */
        Registration: {
            /** @description Name is required */
            name: string;
            /** @description Phone number is required */
            phoneNumber: string;
            /** @description Shop name is required */
            shopName: string;
            /** @description Address is required */
            address: string;
            /** @description Number of cashiers must be at least 1 */
            numberOfCashiers: number;
        };
        /**
         * @example {
         *       "machineId": "machine-123"
         *     }
         */
        MachineQuery: {
            /** @description Machine ID is required */
            machineId: string;
        };
        /**
         * @example {
         *       "licenseKey": "LICENSE-123-ABC",
         *       "machineId": "machine-123",
         *       "issueDate": "2024-01-15T00:00:00.000Z",
         *       "userName": "John Doe",
         *       "shopName": "My Shop"
         *     }
         */
        LicenseKeyResponse: {
            licenseKey?: string | null;
            machineId?: string;
            /** Format: date-time */
            issueDate?: string;
            userName?: string | null;
            shopName?: string | null;
        };
        /**
         * @example {
         *       "users": [
         *         {
         *           "id": 1,
         *           "userName": "John Doe",
         *           "phoneNumber": "+1234567890",
         *           "shopName": "My Shop",
         *           "address": "123 Main St, City, State",
         *           "numberOfCashiers": 2,
         *           "machineId": "machine-123",
         *           "licenseKey": "LICENSE-123-ABC",
         *           "issueDate": "2024-01-15T00:00:00.000Z"
         *         }
         *       ],
         *       "total": 1,
         *       "page": 1,
         *       "limit": 10
         *     }
         */
        AdminUserList: {
            users?: {
                id?: number;
                userName?: string | null;
                phoneNumber?: string | null;
                shopName?: string | null;
                address?: string | null;
                numberOfCashiers?: number | null;
                machineId?: string;
                licenseKey?: string | null;
                /** Format: date-time */
                issueDate?: string;
            }[];
            total?: number;
            page?: number;
            limit?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get item by id */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                    };
                };
            };
        };
    };
}
